### ISSUE TITLE
Errors: "github.com/hashicorp/go-version" imported as fsnotify and not used ; undefined: version

### ISSUE THREAD

**Issue by yurivict** [liip/sheriff#45]
Build of https://github.com/zmap/zdns fails in liip/sheriff:
```
github.com/liip/sheriff
# github.com/liip/sheriff
vendor/github.com/liip/sheriff/sheriff.go:10:2: "github.com/hashicorp/go-version" imported as fsnotify and not used
vendor/github.com/liip/sheriff/sheriff.go:25:14: undefined: version
vendor/github.com/liip/sheriff/sheriff.go:158:26: undefined: version
vendor/github.com/liip/sheriff/sheriff.go:168:26: undefined: version
*** Error code 1
```

FreeBSD 13.2

**Comment by mweibel** [comment]
hmm, please double check if that is really an issue of liip/sheriff. If you look at the mentioned line it doesn't import version as fsnotify (why would we import `version` as `fsnotify` anyway):

https://github.com/liip/sheriff/blob/44f66ae965c04ec00c87d9f1f0f10dca2c710c1f/sheriff.go#L10

I also quickly cloned zdns and could build without any issues. Maybe your vendor directory is messed up? Try deleting it and try again maybe. 

Closing since not a liip/sheriff issue.
